---
-  hosts: test
   become: True
   tasks:
    - name: install python pip
      apt:
        name: python3-pip
        state: present
    - name: install docker
      apt:
        name: docker
        state: present
    - name: start docker
      service: 
        name: docker
        state: started
        enabled: yes
    - name: install docker-py python module
      pip:
       name: docker-py
       state: present
    - name: Log in to the private repository
      docker_login:
        username: harithabondalapati
        password: dckr_pat_8KFsDPNk5BQBQZzwfQKWxPowGSM
        registry_url: docker.io/harithabondalapati/test
      tags:
        - docker  
    - name: Get running containers
      docker_host_info:
        containers: yes
      register: docker_info
    - name: Stop running containers
      docker_container:
        name: "{{ item }}"
        state: stopped
      loop: "{{ docker_info.containers | map(attribute='Id') | list }}"
      failed_when: false
    - name: Remove old container
      docker_container:
        name: test
        state: absent
      tags:
        - docker
    - name: Remove old images
      docker_image:
        name: "{{ item }}"
        state: absent
      with_items:
        - harithabondalapati/test:latest
    - name: Pull the container image from the private repository
      docker_image:
        name: "harithabondalapati/test:latest"
        source: pull
      tags:
        - docker
    - name: run the container
      docker_container:
        name: test
        image: "harithabondalapati/test:latest"
        state: started
        published_ports:
          - "8080:"8080
      tags:
        - docker
