version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:11
    steps:
      - checkout
      - run:
          command: mvn clean install
      - run:
          command: mvn test
workflows:
  version: 2
  build:
    jobs:
      - build
